### PR TITLE
Fixes incorrect id of chat button

### LINKED ISSUE #1121: Slow mode and Timeout countdown broken after twitch update
No longer shows the amount of time until you can next talk due to the button id changing.

Tested with timeouts using an alt account
selection_005

### PR DESCRIPTION
**Pull request by Slikrick**
Timeouts/slowmode countdowns then work properly with the chat button.

Closes #1121

### CODE REVIEW

File: src/features/channel-state.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ var template = require('../templates/channel-state');
 
 var stateContainer = '#bttv-channel-state-contain';
 var chatHeader = '.chat-container .chat-header:first';
-var chatButton = '.chat-interface .chat-buttons-container .send-chat-button';
+var chatButton = '.chat-interface .chat-buttons-container .button.button.primary.float-right';
```
Comment (night) [inline src/features/channel-state.js]: `.button.button` ?
